services:
  backend:
    build: .
    container_name: stage1_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
  db:
    image: postgres:17
    container_name: stage1_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"

volumes:
  postgres_data:
