# Generated by Django 6.0.4 on 2026-04-24 03:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('019dbd7c-6289-7545-97a6-b9616b9f1ca9'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7, verbose_name='Gender')),
                ('gender_probability', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gender probability')),
                ('sample_size', models.PositiveIntegerField(verbose_name='Sample size')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('age_group', models.CharField(choices=[('Child', 'Child'), ('Teenager', 'Teenager'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=10, verbose_name='Age Group')),
                ('country_id', models.CharField(max_length=5, verbose_name='Country ID')),
                ('country_probability', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Country probability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
