# Generated by Django 6.0.4 on 2026-04-29 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, verbose_name='Name')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=7, verbose_name='Gender')),
                ('gender_probability', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gender probability')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('age_group', models.CharField(choices=[('child', 'child'), ('teenager', 'teenager'), ('adult', 'adult'), ('senior', 'senior')], max_length=10, verbose_name='Age Group')),
                ('country_id', models.CharField(max_length=5, verbose_name='Country ID')),
                ('country_name', models.CharField(max_length=75, verbose_name='Country Name')),
                ('country_probability', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Country probability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'indexes': [models.Index(fields=['id', 'name'], name='core_person_id_86eb38_idx')],
            },
        ),
    ]
