# Generated by Django 6.0.4 on 2026-04-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personmodel',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.RenameIndex(
            model_name='personmodel',
            new_name='profiles_id_4e48d7_idx',
            old_name='core_person_id_86eb38_idx',
        ),
        migrations.AlterModelTable(
            name='personmodel',
            table='profiles',
        ),
    ]
