# Generated by Django 6.0.4 on 2026-04-24 03:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='age_group',
            field=models.CharField(choices=[('child', 'child'), ('teenager', 'teenager'), ('adult', 'adult'), ('senior', 'senior')], max_length=10, verbose_name='Age Group'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=7, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('019dbda0-f201-7301-8674-c97b513c5739'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='personmodel',
            index=models.Index(fields=['id', 'name'], name='core_person_id_86eb38_idx'),
        ),
    ]
