# Generated by Django 6.0.4 on 2026-04-24 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_personmodel_age_group_alter_personmodel_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personmodel',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('019dbeea-5144-7063-a596-5f579c1c27e1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Name'),
        ),
    ]
