# Generated by Django 6.0.4 on 2026-04-25 18:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_personmodel_options_alter_personmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('019dc5f8-0ff6-7530-9eb4-fdfc19d00906'), editable=False, primary_key=True, serialize=False),
        ),
    ]
