# Generated by Django 6.0.4 on 2026-04-26 02:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_personmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
