"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ninja',
    'ninja_jwt',
    'rest_framework',
    'corsheaders',
    'core',
    'users'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.CustomLoggerMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


if os.getenv("ENVIRONMENT") == "PRODUCTION":
    DATABASES = {
      'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("PROD_POSTGRES_NAME"),
            'USER': os.getenv("PROD_POSTGRES_USER"),
            'HOST': os.getenv("PROD_POSTGRES_HOST"),
            'PORT': os.getenv('DATABASE_PORT'),
            'PASSWORD': os.getenv('PROD_POSTGRES_PASSWORD'),
            'OPTIONS': {
                'sslmode': 'require',
                'connect_timeout': 20,
            },
            'DISABLE_SERVER_SIDE_CURSORS': True,
            'CONN_HEALTH_CHECKS': True,
            'CONN_MAX_AGE': 0,
        }
    }

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,

        "formatters": {
            "verbose": {
                "format": "{asctime} {levelname} {name} {message}",
                "style": "{",
            },
        },

        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "verbose",
            },
        },

        "root": {
            "handlers": ["console"],
            "level": "INFO",
        },
    }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DEV_POSTGRES_NAME'),
            'USER': os.getenv('DEV_POSTGRES_USER'),
            'HOST': os.getenv('DEV_POSTGRES_HOST'),
            'PASSWORD': os.getenv('DEV_POSTGRES_PASSWORD'),
            'PORT': os.getenv('POSTGRES_PORT')
        }
    }
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "{asctime} {levelname} {name} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "file": {
                "class": "logging.FileHandler",
                "filename": "logger_info.log",
                "formatter": "verbose",
            },
        },
        "loggers": {
            "root": {
                "handlers": ["file"],
                "level": "INFO",
            },
            "ninja_aio": {
                "handlers": ["file"],
                "level": "INFO",
            },
        },
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler"
}

CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL='users.CustomUser'

GITHUB_CLIENT_ID=os.getenv('GITHUB_OAUTH_CLIENT_ID')
GITHUB_CLIENT_SECRET=os.getenv('GITHUB_OAUTH_CLIENT_SECRET')

NINJA_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=3),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=5),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
}

JWT_SECRET= os.getenv('JWT_SECRET')
JWT_SECRET_ALGORITHM= os.getenv('JWT_SECRET_ALGORITHM')
# expity time of token in seconds
JWT_ACCESS_EXP_TIME= timedelta(minutes=60)
JWT_REFRESH_EXP_TIME= timedelta(minutes=120)
